#!name=cookie
#!desc=定时签到脚本的Cookie获取，不用时禁止
#!system=ios

[Script]
# > 京东
# 浏览器登录 https://bean.m.jd.com 点击签到并且出现签到日历
获取京东Cookie = type=http-request,requires-body=1,pattern=^https:\/\/(api\.m|me-api|ms\.jr)\.jd\.com\/(client\.action\?functionId=signBean|user_new\/info\/GetJDUserInfoUnion\?|gw\/generic\/hy\/h5\/m\/appSign\?),script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js

# > 百度贴吧
# 用浏览器访问并登录: https://tieba.baidu.com/index/
tieba.cookie.js = type=http-request,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/tieba/tieba.cookie.js,pattern=^https?:\/\/tieba\.baidu\.com\/?.?

# > 网易云音乐
# 浏览器访问并登录: https://music.163.com/m/login
neteasemusic.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/neteasemusic.cookie.js,type=http-request,pattern=^https?:\/\/music\.163\.com\/?.?

# > 加油广东
gdoil.cookie.js = type=http-request,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/gdoil/gdoil.cookie.js,pattern=^https:\/\/m.gdoil.cn\/webapi\/usersign\/addusersign

# > zaker app
zaker.js = type=http-request,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/zaker/zaker.js,pattern= ^https:\/\/iphone\.myzaker\.com\/zaker\/sign_in\/\/api\/sign_in\.php

# > 途虎养车
途虎养车.js = type=http-request,script-path=https://raw.githubusercontent.com/photonmang/quantumultX/master/tuhu/tuhu.Cookie.js,pattern= ^https://api.tuhu.cn/User/GetUserCurrentAndNextGradeInfo

# > 作业帮
作业帮.js = type=http-request,script-path=https://gitee.com/photonmang/quantumultX/raw/master/zyb.js,pattern= https://napi.zuoyebang.com/napi/signin/signinpage

# > 小米运动
小米运动获取Token = type=http-request,pattern=https:\/\/account(\-cn2)?\.huami\.com(.*)\/login, requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/dompling/Script/master/xmSportsCookieTask.js

[MITM]
hostname = %APPEND% tieba.baidu.com, m.gdoil.cn, music.163.com, iphone.myzaker.com, mqqapi.reader.qq.com, napi.zuoyebang.com, api.tuhu.cn, *.huami.com
