#!name=cookie
#!desc=定时签到脚本的Cookie获取，不用时禁止
#!system=ios

[Script]
# > 京东
# 浏览器登录 https://bean.m.jd.com 点击签到并且出现签到日历
JD_DailyBonus.js = type=http-request,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js,max-size=0,pattern=https:\/\/api\.m\.jd\.com\/client\.action.*functionId=signBean(Index|GroupStageIndex)

# > 百度贴吧
# 用浏览器访问并登录: https://tieba.baidu.com/index/
tieba.cookie.js = type=http-request,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/tieba/tieba.cookie.js,pattern=^https?:\/\/tieba\.baidu\.com\/?.?

# > 网易云音乐
# 浏览器访问并登录: https://music.163.com/m/login
neteasemusic.cookie.js = script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/neteasemusic/neteasemusic.cookie.js,type=http-request,pattern=^https?:\/\/music\.163\.com\/?.?

# > 人人视频
rrtv.cookie.js = type=http-request,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/rrtv/rrtv.cookie.js,pattern=^https:\/\/api\.rr\.tv\/user\/profile

# > 顺丰速运
sfexpress.cookie.js = type=http-request,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/sfexpress/sfexpress.cookie.js,pattern=^https:\/\/sf-integral-sign-in.weixinjia.net\/app\/index
sfexpress.cookie.js = type=http-request,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/sfexpress/sfexpress.cookie.js,pattern=^https:\/\/mcs-mimp-web.sf-express.com\/mcs-mimp\/share\/(.*?)Redirect

# > 加油广东
gdoil.cookie.js = type=http-request,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/gdoil/gdoil.cookie.js,pattern=^https:\/\/m.gdoil.cn\/webapi\/usersign\/addusersign

# > 京东到家 (By @barrymchen, @GideonSenku & @Macsuny)
jddj.js = type=http-request,script-path=https://raw.githubusercontent.com/Sunert/Scripts/master/Task/jddj.js,pattern=https:\/\/daojia\.jd\.com\/client\?_jdrandom=\d{13}&functionId=%2Fsignin

# > 微信小程序 来客有礼
lkyl.js = type=http-request,script-path=https://raw.githubusercontent.com/Sunert/Scripts/master/Task/lkyl.js,pattern=https:\/\/draw\.jdfcloud\.com\/\/api\/bean\/square\/silverBean\/task\/get\?

# > 微信小程序 活动抽奖 (By @makexp & @zZPiglet)
WeChatLottery_new.js = type=http-request,script-path=https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Task/WeChatLottery_new.js,pattern=^https:\/\/api-hdcj\.9w9\.com\/v\d\/sign

# > zaker app
zaker.js = type=http-request,script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/zaker/zaker.js,pattern= ^https:\/\/iphone\.myzaker\.com\/zaker\/sign_in\/\/api\/sign_in\.php

[MITM]
hostname = %APPEND% tieba.baidu.com, api-hdcj.9w9.com, draw.jdfcloud.com, daojia.jd.com, m.gdoil.cn, mcs-mimp-web.sf-express.com, sf-integral-sign-in.weixinjia.net, music.163.com, iphone.myzaker.com
