#!name=自用去开屏广告 Mock
#!desc=极速版JD、KFC、云鲸智能、富途牛牛、发现精彩、车来了、作业帮、小爱音箱去广告

[URL Rewrite]
# 极速版JD
^https://api.m.jd.com/client.action?functionId=lite_advertising - reject
# 微信小程序，交作业app
^https:\/\/mp\.nezhazy\.cn\/student\/ad\/ - reject
#KFC
^https:\/\/res\.kfc\.com\.cn/CRM/kfcad/pop/ - reject
# > top widget@ddgksf2013
https://top-widgets-api.xiaozujian.com/api/ad/config - reject
# > 攔截100@ddgksf2013
https://tagit.hyhuo.com/recover/list - reject

#作业帮*.zybang\.com
^https?:\/\/syh\.zybang\.com\/com\/adx\/impress - reject
^https?:\/\/adx\.zuoyebang\.com - reject
^https?\:/\/jiazhang\.zuoyebang\.com\/parent/activity/actentrance - reject

[Map Local]
# 云鲸智能
#云鲸智能 #开屏广告 #主机名cn-app.narwaltech.com
^https:\/\/cn-app\.narwaltech\.com\/operate\/appPosition\/listSplash\?resourceIds=narwal_splash_screen data-type=text data="{}" status-code=200 
#云鲸智能 #设备横幅广告
^https:\/\/cn-app\.narwaltech\.com\/operate\/cactivity\/listByResourceIds\?resourceIds=index_banner data-type=text data="{}" status-code=200 
#云鲸智能 #我的横幅广告 
^https:\/\/cn-app\.narwaltech\.com\/operate\/cactivity\/listByResourceIds\?resourceIds=user_center_banner data-type=text data="{}" status-code=200 

# > 发现精彩
# hostname = static.95508.com
# 开屏广告
^https?:\/\/static\.95508\.com\/mmg\/images\/ads\/.+\/(.+1125?.+2436|.+%.+%|.+_.+_) data-type=text data="{}" status-code=200
^https?:\/\/static\.95508\.com\/mmg\/ciop\/sysabbr\/cmep\/images\/apppopupads data-type=text data="{}" status-code=200

# > 富途牛牛
# hostname = api*.futunn.com
# 我的横幅广告
^https?:\/\/api\.futunn\.com\/v2\/optimus\/my-homepage-config data-type=text data="{}" status-code=200
# 账户和交易横幅广告
^https?:\/\/api\.futunn\.com\/v2\/config\/promote-config data-type=text data="{}" status-code=200
^https?:\/\/api\d\.futunn\.com\/ad\/ data-type=text data="{}" status-code=200
^https?:\/\/api\.futunn\.com\/v\d\/ad\/ data-type=text data="{}" status-code=200
# 首页右下角角标
^https?:\/\/api\.futunn\.com\/treasure-chest\/box-data data-type=text data="{}" status-code=200

# > chelaile
^https?:\/\/web\.chelaile\.net\.cn\/api\/adpub\/ad data-type=text data="{}" status-code=200
^https?:\/\/cdn\.\w{3}\.chelaileapp\.cn\/(api\/)?adpub data-type=text data="{}" status-code=200
^https?:\/\/api.chelaile.net.cn\/adpub\/ data-type=text data="{}" status-code=200
^https?:\/\/api.chelaile.net.cn\/goocity\/advert\/ data-type=text data="{}" status-code=200
^https?:\/\/atrace.chelaile.net.cn\/adpub\/ data-type=text data="{}" status-code=200
^https?:\/\/atrace.chelaile.net.cn\/exhibit\?&adv_image data-type=text data="{}" status-code=200
^https?:\/\/pic1.chelaile.net.cn\/adv\/ data-type=text data="{}" status-code=200

# > 钉钉
# hostname = gw.alicdn.com, img.alicdn.com
# 误杀少 解决阿里系的开屏 目前测试咸鱼/钉钉 感谢【zzzzzz】分享
^https?:\/\/(gw|img)\.alicdn\.com\/imgextra\/.+\/[\w!]+\d+-\d+-.+-\b([8-9]\d{2,}|[1-9]\d{3,})\b-\b([5-9]\d{2,}|[1-9]\d{3,})\b data-type=text data="{}" status-code=200

#央视频cdn.cmgadx.com
#^https:\/\/cdn\.cmgadx\.com\/sdk\/pool\/ data-type=text data="{}" status-code=200

#小爱音箱cdn.cmgadx.cominfo.mina.xiaoaisound.com
^https?:\/\/info\.mina\.xiaoaisound\.com\/(advertise|payGuide)\/ data-type=text data='{ "code": 0, "message": "Success", "data": [] }' header='Content-Type:application/json'


[MITM]
hostname = %APPEND% res.kfc.com,top-widgets-api.xiaozujian.com,tagit.hyhuo.com,mp.nezhazy.cn,cn-app.narwaltech.com,static.95508.com,api*.futunn.com,*.chelaile.net.cn,img.alicdn.com,syh.zybang.com,adx.zuoyebang.com,jiazhang.zuoyebang.com,info.mina.xiaoaisound.com
