#!name=自用去开屏广告
#!desc=极速版JD、KFC、加油广东

[URL Rewrite]

# 极速版JD
^https://api.m.jd.com/client.action?functionId=lite_advertising - reject
# 微信小程序，交作业app
^https:\/\/mp\.nezhazy\.cn\/student\/ad\/ - reject
#KFC
^https:\/\/res\.kfc\.com\.cn/CRM/kfcad/pop/ - reject
# gdoil
^https:\/\/m\.gdoil\.cn\/gd\/sys\/getStartUpAd - reject
# > top widget@ddgksf2013
https://top-widgets-api.xiaozujian.com/api/ad/config - reject
# > 攔截100@ddgksf2013
https://tagit.hyhuo.com/recover/list - reject
# > 02 虎扑@ddgksf2013
^https?:\/\/i\d\.hoopchina\.com\.cn/blogfile\//d+\//d+\/BbsImg\.(?<=(big.(png|jpg)))$ - reject
^https?:\/\/games\.mobileapi\.hupu\.com\/.+\/(search|interfaceAdMonitor|status|hupuBbsPm)/(hotkey|init|hupuBbsPm)\. - reject
^https?:\/\/games\.mobileapi\.hupu\.com\/interfaceAdMonitor url - reject
^https?:\/\/goblin\.hupu\.com\/.+\/interfaceAd\/getOther - reject
^https?:\/\/i1\.hoopchina\.com\.cn\/blogfile\/.+_\d{3}x\d{4} - reject
# > 100 车来了@ddgksf2013
^https?:\/\/cdn\.\w{3}\.chelaileapp\.cn\/(api\/)?adpub - reject
# > 44 车来了
^https?:\/\/api.chelaile.net.cn\/adpub\/ - reject
^https?:\/\/api.chelaile.net.cn\/goocity\/advert\/ - reject
^https?:\/\/atrace.chelaile.net.cn\/adpub\/ - reject
^https?:\/\/atrace.chelaile.net.cn\/exhibit\?&adv_image - reject
^https?:\/\/pic1.chelaile.net.cn\/adv\/ - reject


[MITM]
hostname = %APPEND% mp.nezhazy.cn,res.kfc.com,m.gdoil.cn,top-widgets-api.xiaozujian.com,tagit.hyhuo.com,goblin.hupu.com,*.hoopchina.com,games.mobileapi.hupu.com,api.chelaile.net.cn,atrace.chelaile.net.cn,top-widgets-api.xiaozujian.com
