#!name=自用去开屏广告
#!desc=极速版JD、KFC、加油广东、去鲸智能

[URL Rewrite]
# 极速版JD
^https://api.m.jd.com/client.action?functionId=lite_advertising - reject
# 微信小程序，交作业app
^https:\/\/mp\.nezhazy\.cn\/student\/ad\/ - reject
#KFC
^https:\/\/res\.kfc\.com\.cn/CRM/kfcad/pop/ - reject
# > top widget@ddgksf2013
https://top-widgets-api.xiaozujian.com/api/ad/config - reject
# > 攔截100@ddgksf2013
https://tagit.hyhuo.com/recover/list - reject
# 云鲸智能
#云鲸智能 #开屏广告 #主机名cn-app.narwaltech.com
^https:\/\/cn-app\.narwaltech\.com\/operate\/appPosition\/listSplash\?resourceIds=narwal_splash_screen - reject-drop
#云鲸智能 #设备横幅广告
^https:\/\/cn-app\.narwaltech\.com\/operate\/cactivity\/listByResourceIds\?resourceIds=index_banner - reject-drop
#云鲸智能 #我的横幅广告 
^https:\/\/cn-app\.narwaltech\.com\/operate\/cactivity\/listByResourceIds\?resourceIds=user_center_banner - reject-drop

[MITM]
hostname = %APPEND% res.kfc.com,top-widgets-api.xiaozujian.com,tagit.hyhuo.com,mp.nezhazy.cn,cn-app.narwaltech.com
