#!name=Panels
#!desc=信息面板

[Panel]
策略面板 = script-name=缓存开关,update-interval=15
//策略面板 = script-name=奈飞查询,update-interval=3600
策略面板 = script-name=代理选择,update-interval=60

[Script]
缓存开关 = type=generic,timeout=10,script-path=https://raw.githubusercontent.com/githubdulong/Script/master/surgepro_flushdns.js,argument=icon=crown.fill&color=#f4a460&title=𝘚𝘶𝘳𝘨𝘦｜2023-02-20
//奈飞查询 = type=generic,timeout=30,script-path=https://raw.githubusercontent.com/githubdulong/Script/master/nf_check.js,argument=icon=checkmark.circle&color=#4682b4&title=𝘕𝘦𝘵𝘧𝘪𝘹
代理选择 = type=generic,timeout=10,script-path=https://raw.githubusercontent.com/fishingworld/something/main/groupPanel.js,argument=icon=bolt.circle&color=#4682b4&group=𝘗𝘳𝘰𝘹𝘺
