#!name=Panels
#!desc=信息面板

[Panel]
#Surge Pro标题,可显示启动时间,点击刷新为重载配置
SurgePro_ReloadProfile = script-name=SurgePro_ReloadProfile,update-interval=1

#流量统计
TrafficStatistics = script-name=TrafficStatistics,update-interval=1


[Script]
#附带重载配置,Surge Pro标题,可显示启动时间,点击刷新为重载配置
SurgePro_ReloadProfile = type=generic,timeout=10,script-path= https://raw.githubusercontent.com/fishingworld/something/main/PanelScripts/surgepro_reloadprofile.js ,argument=icon=crown.fill&color=#f6c970

#流量统计 点击以切换网络界面
TrafficStatistics = type=generic,timeout=10,script-path= https://raw.githubusercontent.com/fishingworld/something/main/PanelScripts/trafficstatistics.js ,argument=icon=arrow.up.arrow.down.circle&color=#5d84f8
