#!name=iOS Tasks Module
#!desc=iOS Tasks 模块配置

[Script]
京东领豆 = type=cron,cronexp=15 1 0,9 * * *,wake-system=1,timeout=600,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js
途虎养车 = type=cron,cronexp=15 12 8 * * *,wake-system=1,timeout=20,script-path=https://raw.githubusercontent.com/photonmang/quantumultX/master/tuhu/tuhu.js
作业帮 = type=cron,cronexp=15 13 8 * * *,wake-system=1,timeout=20,script-path=https://raw.githubusercontent.com/photonmang/quantumultX/master/Task/zyb.js
