#!name = 微信小程序去广告
#!desc = 收录常用小程序的去广告，作者署名在插件内。
#!openUrl = https://apps.apple.com/app/id414478124
#!author = 可莉🅥[https://gitlab.com/lodepuly/vpn_tool/-/blob/master/README.md]
#!tag = 去广告

[Rule]
# 微信小程序通用规则
DOMAIN,wxsnsdy.wxs.qq.com,REJECT,extended-matching,pre-matching
DOMAIN,wxsmsdy.video.qq.com,REJECT,extended-matching,pre-matching
DOMAIN,wxsnsdythumb.wxs.qq.com,REJECT,extended-matching,pre-matching

[URL Rewrite]
# 货拉拉 qapi.huolala.cn, appuser-static.huolala.cn
^https:\/\/qapi\.huolala\.cn\/ads - reject
^https:\/\/qapi\.huolala\.cn\/home_new_user - reject
^https:\/\/qapi\.huolala\.cn\/get_service_list - reject
^https:\/\/appuser-static\.huolala\.cn\/imgs - reject
# 蜜雪冰城 mxsa.mxbc.net
^https:\/\/mxsa\.mxbc\.net\/api\/v1\/adinfo\/adplace\/query - reject
# 德邦快递 www.deppon.com
^https:\/\/www\.deppon\.com\/gwapi\/memberService\/eco\/member\/grade\/commonInterface - reject
# 猫眼电影
# 弹窗广告+横幅广告 # 主机名ad.maoyan.com
^https:\/\/ad\.maoyan\.com\/api\/position\/detail - reject
# 电竞赛事+热门赛事 # 主机名wx.maoyan.com
^https:\/\/wx\.maoyan\.com\/maoyansh\/api\/mobile\/(hotMatchList|eSportsIps) - reject
# 猫眼放映厅 # 主机名vod-movie.maoyan.com
^https:\/\/vod-movie\.maoyan\.com\/vod\/video\/onlineMovies\.json - reject
# 顺丰速运+ @可莉🅥
^https:\/\/ucmp\.sf-express\.com\/proxy\/operation-platform\/info-flow-adver\/query - reject
^https:\/\/ucmp\.sf-express\.com\/proxy\/esgcempcore\/memberGoods\/pointMallService\/goodsList - reject
# 滴滴代驾 daijia.kuaidadi.com, as.xiaojukeji.com
^https:\/\/as\.xiaojukeji\.com\/ep\/as\/conf\?ns=daijia-front&name= - reject
^https:\/\/daijia\.kuaidadi\.com\/gateway\?api=prado\.cms\.delivery\.batch&apiVe - reject

[Map Local]
# 移除公众号中的推广内容 //mp.weixin.qq.com
^http:\/\/\w+\.wxs\.qq\.com\/\d+\/\d+\/(snscosdownload|snssvpdownload)\/(SH|SZ)\/reserved\/\w+ data-type=text data="{}" status-code=200
^https:\/\/mp\.weixin\.qq\.com\/mp\/(cps_product_info|getappmsgad|jsmonitor|masonryfeed|relatedarticle)\? data-type=text data="{}" status-code=200
# 必胜客 res.pizzahut.com.cn
^https:\/\/res\.pizzahut\.com\.cn\/CRM data-type=text data="{}" status-code=200
# 麦当劳 api.mcd.cn
^https:\/\/api\.mcd\.cn\/bff\/portal\/home\/hotActivity data-type=text data="{}" status-code=200
# 神州租车 apiproxy.zuche.com
^https:\/\/apiproxy\.zuche\.com\/resource\/carrctapi\/home\/marketing data-type=text data="{}" status-code=200
# 哈啰 api.hellobike.com
^https:\/\/api\.hellobike\.com\/api\?adx data-type=text data="{}" status-code=200
# 滴滴青桔 htwkop.xiaojukeji.com
^https:\/\/htwkop\.xiaojukeji\.com\/gateway\?api=cms\.htw\.delivery data-type=text data="{}" status-code=200
^https:\/\/htwkop\.xiaojukeji\.com\/gateway\?api=hm\.fa\.combineHomepageInfo data-type=text data="{}" status-code=200
^https:\/\/htwkop\.xiaojukeji\.com\/gateway\?api=hm\.fa\.mallRecommend data-type=text data="{}" status-code=200
# 途虎养车小程序 @张军
^https:\/\/mkt-gateway\.tuhu\.cn\/mkt-scene-marketing-service\/api\/scene\/queryScheme data-type=text data="{}" status-code=200

[MITM]
hostname = %APPEND% res.pizzahut.com.cn, mp.weixin.qq.com, api.mcd.cn,qapi.huolala.cn, appuser-static.huolala.cn,mxsa.mxbc.net,www.deppon.com,www.deppon.com,ad.maoyan.com,wx.maoyan.com,vod-movie.maoyan.com,ucmp.sf-express.com,daijia.kuaidadi.com, as.xiaojukeji.com, apiproxy.zuche.com, api.hellobike.com, htwkop.xiaojukeji.com, mkt-gateway.tuhu.cn
