#!name=ZTJY AD
#!desc=掌通家园去广告
#!system=ios

[URL Rewrite]
^https://adlog-ztjy.szy.cn/ad/ - reject
^https://api-access.pangolin-sdk-toutiao.com/api/ad/ - reject
^http://snsimg.ztjystore.cn/ztnew/ad/ - reject
^https://ztjy.cn-hangzhou.log.aliyuncs.com/logstores/sdo_bfn_adv/ - reject
^https://ztjy.cn-hangzhou.log.aliyuncs.com/logstores/ztjy_ad/ - reject

[MITM]
hostname = %APPEND% adlog-ztjy.szy.cn, api-access.pangolin-sdk-toutiao.com, snsimg.ztjystore.cn, ztjy.cn-hangzhou.log.aliyuncs.com
